[ansible@controlnode ansible]$ cat hosts.sample.j2
{% for host in groups['all'] %}

{{ hostvars[host]['ansible_facts']['default_ipv4']['address'] }} {{ hostvars[host]['ansible_facts']['fqdn'] }} {{ hostvars[host]['ansible_facts']['hostname'] }}

{% endfor %}

---
- name: Creating /etc/myhosts file in all nodes
  hosts: all
  tasks:
    - name: Using jinja2 template to create a file
      ansible.builtin.template:
        src: hosts.sample.j2
        dest: /etc/myhosts
      when: " 'webserver' in group_names"
